---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 01.12.2021 19:01
---
---
---



function InitInputHandler (data)
    nimValueToExtend = 1 / 4 * 128
    data.Points = {}
    data.Effects = {}
    data.sides = {}
    data.previousDirection = 0
    data.AnglePoints={} --таблица точек, которая хранит углы
end

function ClearPoints(data)
    data.Points = {}
    --print("очистка")
    for i = 1, #data.Effects do
        --print("clearEffects",i)
       -- BlzSetSpecialEffectPosition(data.Effects[i],-5000,-5000,0)
        DestroyEffect(data.Effects[i])
    end
    data.Effects = {}
    data.AnglePoints={}
end

function InputUpdate (data, x, y)
    --local x, y = data.fakeX, data.fakeY --GetPlayerMouseX[data.pid], GetPlayerMouseY[data.pid]
    local vector = Vector:new(x, y, 0)
    if data.LMBIsPressed or (data.LastCastName=="icewall" and data.RMBIsPressed) then
        --print(#Points,Points[#Points])
        if (#data.Points > 0 and
                DistanceBetweenXY(x, y, data.Points[#data.Points].x, data.Points[#data.Points].y) < nimValueToExtend) then
            --print("обрыв")
            return
        end
        table.insert(data.Points, vector)
        --print("insert OK")
        UnitAddMana(data.UnitHero,-1)
        table.insert(data.Effects, CreateTMPEffect(x, y,"Doodads\\Cinematic\\GlowingRunes\\GlowingRunes"..data.inputEffectNumber )) -- "Abilities\\Spells\\Items\\HealingSalve\\HealingSalveTarget.mdl"--"units\\nightelf\\Wisp\\Wisp"

        ShapeDetectorAdd(data.Points[#data.Points],
                #data.Points <= 1 and 0 or data.Points[#data.Points - 1], data)
    end
end