---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 18.03.2022 1:56
---
function InitSpellPanel(data)
    print("создана локальная панель контейнер")
    data.SpellPanelContainer=BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), '', 0)
    BlzFrameSetVisible(data.SpellPanelContainer,GetLocalPlayer()==GetOwningPlayer(data.UnitHero))
    for i=1,10 do
        AddSpell2DataByName(data, "Charge")
    end
end