---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 18.03.2022 2:55
---
function TargetCatcher(data, x, y, radius)
    local e = nil
    local k = 0
    local enemy = nil
    GroupEnumUnitsInRange(perebor, x, y, radius, nil)
    while true do
        e = FirstOfGroup(perebor)
        if e == nil then
            break
        end
        if UnitAlive(e) and IsUnitEnemy(e, GetOwningPlayer(data.UnitHero)) and not enemy then
            k = k + 1
            enemy = e
            print("цель захвачена")
            if not data.MainTarget then
                data.MainTarget = enemy
            else
                if data.MainTarget == enemy then
                    print("цель захвачена повторно")
                else
                    print("Захвачена новая цель")
                    data.MainTarget = enemy
                end
            end
        end

        GroupRemoveUnit(perebor, e)
    end
    if not enemy then
        print("очистка цели")
        data.MainTarget = nil
    end
    return enemy
end