---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 24.11.2021 19:59
---
function EffectFromUnit2Unit(eff, effModel, hero, enemy, flag)
    local x, y = GetUnitXY(enemy)
    local xEnd, yEnd = GetUnitXY(hero)
    local z = 80
    if not eff then
        eff = AddSpecialEffect(effModel, x, y)
    end
    BlzSetSpecialEffectPosition(eff, x, y, z)
    local angle = AngleBetweenXY(x, y, xEnd, yEnd) / bj_DEGTORAD
    local angleFake = angle - 45
    --BlzSetSpecialEffectScale(eff, 0.1)
    local d = 0
    TimerStart(CreateTimer(), TIMER_PERIOD64, true, function()
        d = d + 1
        angleFake = angleFake + 7
        angle = AngleBetweenXY(x, y, xEnd, yEnd) / bj_DEGTORAD
        x, y = MoveXY(x, y, 20, angle)
        BlzSetSpecialEffectPosition(eff, x, y, z)
        --BlzSetSpecialEffectScale(eff, 0.1)
        xEnd, yEnd = GetUnitXY(hero)
        if DistanceBetweenXY(x, y, xEnd, yEnd) <= 50 or d >= 100 then
            DestroyTimer(GetExpiredTimer())
            DestroyEffect(eff)
            if flag == "add gold" then
                local gain = BlzGetUnitMaxHP(enemy) / 100
                if gain < 1 then
                    gain = 1
                end
                UnitAddGold(hero, R2I(gain))
            elseif flag == "eating" then
                --print("скушал яблочко")
            end
            --print("долетел")
        end
    end)
end

function EffectFromPoint2Unit(eff, effModel, hero, x, y, flag)
    local xEnd, yEnd = GetUnitXY(hero)
    local z = GetTerrainZ(xEnd, yEnd)--+80

    if not eff then
        eff = AddSpecialEffect(effModel, x, y)
    end
    BlzSetSpecialEffectPosition(eff, x, y, z)
    local angle = AngleBetweenXY(x, y, xEnd, yEnd) / bj_DEGTORAD
    local angleFake = angle - 45
    local speed = 20
    --BlzSetSpecialEffectScale(eff, 0.1)
    local d = 0
    local fixZ = 0
    TimerStart(CreateTimer(), TIMER_PERIOD64, true, function()
        d = d + 1
        angleFake = angleFake + 7
        angle = AngleBetweenXY(x, y, xEnd, yEnd) / bj_DEGTORAD
        x, y = MoveXY(x, y, speed, angle)
        local zEnd = GetTerrainZ(xEnd, yEnd) + 80
        --local zWay=DistanceBetweenXY(x, y, xEnd, yEnd)/speed
        --local zStep=zEnd-BlzGetLocalSpecialEffectZ(eff)/zWay
        --print(zStep,zWay)
        fixZ = fixZ + 5
        if fixZ > zEnd then
            fixZ = zEnd
        end
        BlzSetSpecialEffectPosition(eff, x, y, GetTerrainZ(x, y) + fixZ)
        --BlzSetSpecialEffectScale(eff, 0.1)
        xEnd, yEnd = GetUnitXY(hero)
        if DistanceBetweenXY(x, y, xEnd, yEnd) <= 50 or d >= 100 then
            DestroyTimer(GetExpiredTimer())
            DestroyEffect(eff)
            if flag == "add gold" then
                print("функция не на свём месте")
            elseif flag == "eating" then
                print("скушал яблочко")
                local up=0.1
                local snd=normal_sound("MP3\\Isaac\\GrowUp", x, y)
                local grow=1+up*GetUnitUserData(hero)
                SetSoundPitch(snd,grow )
                SetUnitUserData(hero,GetUnitUserData(hero)+1)
                SetUnitScale(hero,grow,grow,grow)
            end
            --print("долетел")
        end
    end)
end


