---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 25.12.2021 16:44
---
function AddMaxLife(hero, amount)
    local maxHP = BlzGetUnitMaxHP(hero)
    if IsUnitType(hero,UNIT_TYPE_HERO) then
        local data=GetUnitData(hero)
        amount=R2I(amount*data.MaxLifeBonus)
        if data.HealForHeart then
            HealUnit(hero,maxHP)
        end
    end

    BlzSetUnitMaxHP(hero, maxHP + amount)
    if IsUnitType(hero,UNIT_TYPE_HERO) then
        TimerStart(CreateTimer(), 1, false, function()
            FlyTextTagHealXY(GetUnitX(hero), GetUnitY(hero), "+" .. R2I(amount)..L(" Макс ХП"," Max HP"), GetOwningPlayer(hero))
            DestroyTimer(GetExpiredTimer())
        end)
    else
        HealUnit(hero)
    end
    --HealUnit(hero, amount)
end