---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 19.12.2021 0:20
---

BDItems = {
    ["Slime Card"]  = {
        descriptions = "Постоянное увеличение ХП на 50",
        effModel     = "SpecialItemWhite",
        ico          = "card",
        cost         = "100",
        lvl          = 1,
        short        = "HP UP",
        drop         = 2,
    },
    ["Slime Jelly"] = {
        descriptions = "Исцеляет на 50 единиц при подборе",
        effModel     = "",
        ico          = "ReplaceableTextures\\CommandButtons\\BTNPhilosophersStone.blp",
        cost         = "100",
        lvl          = 1,
        short        = "Heal",
        drop         = 20,
        canUsed      = true,
    },
    ["Slime Egg"]   = {
        descriptions = "Призывает слайма который всегда сражается на вашей стороне, стаки увеличивает здоровье слайма",
        effModel     = "",
        ico          = "ReplaceableTextures\\CommandButtons\\BTNPhoenixEgg.blp",
        cost         = "100",
        lvl          = 1,
        short        = "Summon Slime",
        drop         = 2,
    },
    ["Apple"]       = {
        descriptions = "Восстанавливает 10 здоровья",
        effModel     = "",
        ico          = "Icons\\RO\\apple",
        cost         = "100",
        lvl          = 1,
        short        = "Small Heal",
        drop         = 20,
        canUsed      = true,
    },
    ["Bag Card"]    = {
        descriptions = "Заклинание Sand Storm, будет призывать по 1 жуку за каждую карту в инвентаре, при убийстве врагов",
        effModel     = "SpecialItemWhite",
        ico          = "card",
        cost         = "100",
        lvl          = 1,
        short        = "Summon Per Kill",
        drop         = 2,
    },
    ["Shell"]       = {
        descriptions = "+1 брони за каждый стак",
        effModel     = "SpecialItemWhite",
        ico          = "card",
        cost         = "100",
        lvl          = 1,
        short        = "Armor Up",
        drop         = 5,
    },
    ["Rat Card"]    = {
        descriptions = "Увеличивает любой шанс дропа на 1%% за каждый стак",
        effModel     = "SpecialItemWhite",
        ico          = "card",
        cost         = "100",
        lvl          = 1,
        short        = "Drop Up",
        drop         = 2,
    },
    ["Murloc Mutant Card"]    = {
        descriptions = "Волна наносит 50 доп урона за каждый стак, если толкает юнита в стену",
        effModel     = "SpecialItemWhite",
        ico          = "card",
        cost         = "100",
        lvl          = 1,
        short        = "Drop Up",
        drop         = 2,
    },
}