---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 18.12.2021 19:35
---
function InitInventory(data)
    local BoxFrame = CreateInventoryBox(data)

    local invFH = CreateInventoryButton(data, nil, BoxFrame)
    CreateActionBox(data, invFH)
    CreateRmbTips(data, invFH)
    BlzFrameSetVisible(BoxFrame, false)
end
function CreateInventoryButton(data, texture, BoxFrame)
    if not texture then
        texture = "ReplaceableTextures\\CommandButtons\\BTNDust.blp"
    else

    end
    local SelfFrame = BlzCreateFrameByType('GLUEBUTTON', 'FaceButton', BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), 'ScoreScreenTabButtonTemplate', 0)
    local buttonIconFrame = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', SelfFrame, '', 0)

    BlzFrameSetParent(SelfFrame, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetParent(buttonIconFrame, BlzGetFrameByName("ConsoleUIBackdrop", 0))


    --BlzFrameSetVisible(SelfFrame, false)
    -- BlzFrameSetVisible(SelfFrame, GetLocalPlayer() == player)
    BlzFrameSetAllPoints(buttonIconFrame, SelfFrame)
    BlzFrameSetTexture(buttonIconFrame, texture, 0, true)
    BlzFrameSetSize(SelfFrame, GNext, GNext)
    BlzFrameSetAbsPoint(SelfFrame, FRAMEPOINT_CENTER, 0.8 + GNext / 2, GNext / 2)

    local ClickTrig = CreateTrigger()
    BlzTriggerRegisterFrameEvent(ClickTrig, SelfFrame, FRAMEEVENT_CONTROL_CLICK)
    TriggerAddAction(ClickTrig, function()
        if BlzFrameIsVisible(BoxFrame) then
            BlzFrameSetVisible(BoxFrame, false)
        else
            BlzFrameSetVisible(BoxFrame, GetLocalPlayer() == GetTriggerPlayer())
        end

        BlzFrameSetEnable(BlzGetTriggerFrame(), false)
        BlzFrameSetEnable(BlzGetTriggerFrame(), true)
        StopUnitMoving(data)
    end)

    local TrigMOUSE_ENTER = CreateTrigger()
    BlzTriggerRegisterFrameEvent(TrigMOUSE_ENTER, SelfFrame, FRAMEEVENT_MOUSE_ENTER)

    TriggerAddAction(TrigMOUSE_ENTER, function()

        --print("показать подсказку ",flag)
        --callENTER()

        --  BlzFrameSetAbsPoint(ttBox, FRAMEPOINT_CENTER, 0, GHandY)


    end)
    local TrigMOUSE_LEAVE = CreateTrigger()
    BlzTriggerRegisterFrameEvent(TrigMOUSE_LEAVE, SelfFrame, FRAMEEVENT_MOUSE_LEAVE)
    TriggerAddAction(TrigMOUSE_LEAVE, function()

        --print("убрать подсказку")
        --callLEAVE()
        --  BlzFrameSetVisible(ttBox, false)
        --BlzFrameSetVisible(tt[1],false)
    end)

    ---Подсказка
    local text = BlzCreateFrameByType("TEXT", "ButtonChargesText", SelfFrame, "", 0)
    BlzFrameSetParent(text, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetText(text, "TAB")
    BlzFrameSetScale(text, 1)
    BlzFrameSetPoint(text, FRAMEPOINT_TOP, SelfFrame, FRAMEPOINT_TOP, 0.00, 0.01)

    return SelfFrame, buttonIconFrame
end

function CreateInventoryBox(data)
    local x, y = 0.624, 0.175 + GNext
    local BoxFrame = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), '', 0)
    local m = 1

    for i = 1, 5 do
        for k = 1, 5 do
            data.ItemSlot[m], data.ItemSlotTexture[m], data.ItemSlotName[m], data.ItemSlotTooltip[m], data.ItemSlotText[m] = CreateEmptySlot(data, x + (k - 1) * GNext, y - (i - 1) * GNext, BoxFrame, m)
            m = m + 1
        end
    end
    data.BoxFrame = BoxFrame
    return BoxFrame
end
GNext = 0.039
function CreateEmptySlot(data, x, y, parent, m)
    local name = "empty_slot"
    local preBackdrop = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', parent, '', 0)
    local SelfFrame = BlzCreateFrameByType('GLUEBUTTON', 'FaceButton', parent, 'ScoreScreenTabButtonTemplate', 0)
    local buttonIconFrame = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', SelfFrame, '', 0)
    local tooltip, backdrop, text = CreateToolTipBox(x, y, parent)
    BlzFrameSetParent(SelfFrame, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetParent(buttonIconFrame, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetParent(preBackdrop, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    -- BlzFrameSetVisible(SelfFrame, false)
    -- BlzFrameSetVisible(SelfFrame, GetLocalPlayer() == player)
    BlzFrameSetAllPoints(buttonIconFrame, SelfFrame)
    BlzFrameSetTexture(buttonIconFrame, name, 0, true)

    BlzFrameSetAllPoints(preBackdrop, SelfFrame)
    BlzFrameSetTexture(preBackdrop, name, 0, true)

    BlzFrameSetSize(SelfFrame, GNext, GNext)
    BlzFrameSetAbsPoint(SelfFrame, FRAMEPOINT_CENTER, x, y)
    --print("создан action", m)
    CreateTriggerActions(data, SelfFrame, tooltip, text, m)

    return SelfFrame, buttonIconFrame, name, tooltip, text
end

function GetFrameFreeSlot(data, name)
    local find = false
    for i = 1, #data.ItemSlot do

        if data.ItemSlotName[i] == name then
            local ch = GetFrameCharges(data.ItemSlotTexture[i])
            --print(ch)
            SetFrameCharges(data.ItemSlotTexture[i], ch + 1)
            --print("у вас уже есть предмет данного типа, пополняем заряды", ch + 1)
            return data.ItemSlotTexture[i], i
        end
        if data.ItemSlotName[i] == "empty_slot" then
            --print("найден пустой слот в позиции",i)
            MakeFrameCharged(data.ItemSlotTexture[i], 1)
            data.ItemSlotName[i] = name
            find = true
            return data.ItemSlotTexture[i], i
        end
    end
    if not find then
        return false
    end
end

function CreateToolTipBox(x, y, parent)
    local tooltip = BlzCreateFrameByType("FRAME", "TestDialog", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), "StandardFrameTemplate", 0)
    local backdrop = BlzCreateFrame("QuestButtonDisabledBackdropTemplate", tooltip, 0, 0)
    local text = BlzCreateFrameByType("TEXT", "ButtonChargesText", tooltip, "", 0)
    --BlzFrameSetParent(tooltip, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetParent(backdrop, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    --BlzFrameSetParent(text, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetAbsPoint(tooltip, FRAMEPOINT_CENTER, x, y + 0.078)
    local sx, sy = 0.2, 0.1
    BlzFrameSetSize(tooltip, sx, sy)
    BlzFrameSetSize(backdrop, sx, sy)
    BlzFrameSetSize(text, sx * .75, sy * .9)
    BlzFrameSetPoint(backdrop, FRAMEPOINT_CENTER, tooltip, FRAMEPOINT_CENTER, 0.0, 0.0)
    BlzFrameSetAlpha(backdrop, 250)
    BlzFrameSetText(text, "Пусто")
    BlzFrameSetPoint(text, FRAMEPOINT_CENTER, backdrop, FRAMEPOINT_CENTER, 0.00, -0.01)
    BlzFrameSetVisible(tooltip, false)
    return tooltip, backdrop, text
end

function CreateTriggerActions(data, SelfFrame, tooltip, text, m)
    local ClickTrig = CreateTrigger()
    BlzTriggerRegisterFrameEvent(ClickTrig, SelfFrame, FRAMEEVENT_CONTROL_CLICK)
    TriggerAddAction(ClickTrig, function()
        --print("клик")
        BlzFrameSetEnable(BlzGetTriggerFrame(), false)
        BlzFrameSetEnable(BlzGetTriggerFrame(), true)
        StopUnitMoving(data)
        ActiveItemActions(data, m)
    end)

    local TrigMOUSE_ENTER = CreateTrigger()
    BlzTriggerRegisterFrameEvent(TrigMOUSE_ENTER, SelfFrame, FRAMEEVENT_MOUSE_ENTER)

    TriggerAddAction(TrigMOUSE_ENTER, function()
        BlzFrameSetVisible(tooltip, GetLocalPlayer() == GetTriggerPlayer())
        UpdateToolTipForItemInSlot(data, text, m)
        --print("показать подсказку ")


    end)
    local TrigMOUSE_LEAVE = CreateTrigger()
    BlzTriggerRegisterFrameEvent(TrigMOUSE_LEAVE, SelfFrame, FRAMEEVENT_MOUSE_LEAVE)
    TriggerAddAction(TrigMOUSE_LEAVE, function()
        BlzFrameSetVisible(tooltip, false)
        --print("убрать подсказку")

    end)
end

function UpdateToolTipForItemInSlot(data, text, m)
    local name = data.ItemSlotName[m]
    --print(name)
    if BDItems[name] then
        BlzFrameSetText(text, ColorText2(name) .. "\n" .. BDItems[name].descriptions)
    end
end

function SetFrameCharges(fh, ch)
    if BlzFrameGetChildrenCount(fh) == 0 then
        MakeFrameCharged(fh, ch)
    else
        local textFrame = BlzFrameGetChild(fh, 1)
        BlzFrameSetText(textFrame, I2S(R2I(ch)))
    end
end

function GetFrameCharges(fh)
    --print("число детей", BlzFrameGetChildrenCount(fh) )
    if BlzFrameGetChildrenCount(fh) == 0 then
        MakeFrameCharged(fh, 1)
        return 1
    else
        --print("заряды уже были", BlzFrameGetChildrenCount(fh) )

        local textFrame = BlzFrameGetChild(fh, 1)
        local chargesBox = BlzFrameGetChild(fh, 0)
        local text = BlzFrameGetText(textFrame)
        --print("найдено зарядов", text)
        return S2I(text), chargesBox, textFrame
    end
end

function MakeFrameCharged(fh, ch)
    local chargesBox = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', fh, '', 0)-- рамка
    BlzFrameSetTexture(chargesBox, "UI\\Widgets\\Console\\Human\\CommandButton\\human-button-lvls-overlay", 0, true)
    BlzFrameSetSize(chargesBox, GNext / 2, GNext / 3)
    BlzFrameSetPoint(chargesBox, FRAMEPOINT_BOTTOMRIGHT, fh, FRAMEPOINT_BOTTOMRIGHT, 0.001, 0.0)
    local text = BlzCreateFrameByType("TEXT", "ButtonChargesText", fh, "", 0)
    BlzFrameSetPoint(text, FRAMEPOINT_CENTER, chargesBox, FRAMEPOINT_CENTER, 0.0, 0.0)
    BlzFrameSetText(text, I2S(R2I(ch)))
    return text
end

function GetFHByName(data, name)
    local find=false
    for i = 1, #data.ItemSlot do
        if data.ItemSlotName[i] == name then
            --local ch = GetFrameCharges(data.ItemSlotTexture[i])
            --print(ch)
            --SetFrameCharges(data.ItemSlotTexture[i], ch + 1)
            --print("у вас уже есть предмет данного типа, пополняем заряды", ch + 1)
            return data.ItemSlotTexture[i], i
        end
    end
       if not find then
        return false
    end
end