---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 18.12.2021 21:48
---
AllItemsTable={}
function CreateItemPrefab(x,y,name,fromEffect)
    local t={}
    local effModel=BDItems[name].effModel
    if not effModel or effModel=="" then
        --print("пустой эффект")
        effModel="BagItem"
    end
    local eff=nil
    if not fromEffect then
        eff=AddSpecialEffect(effModel,x,y)
    else
        eff=fromEffect
    end
    table.insert(t,eff)
    table.insert(t,name)
    table.insert(t,x)
    table.insert(t,y)
    table.insert(AllItemsTable,t)
end

function CreateItemPrefabPool(data,x,y,...)
    local pool ={...}
    for i=1, #pool do
        local drop=BDItems[pool[i]].drop
        local dice=GetRandomInt(1,100)
        --print(drop,dice)
        local fh=GetFHByName(data,"Rat Card")
        if fh then
            local ch=GetFrameCharges(fh)
            drop=drop+ch
        end
        if dice<=drop then
            local xn,yn=MoveXY(x,y,GetRandomInt(1,50),GetRandomInt(0,360))
            CreateItemPrefab(xn,yn,pool[i])
        end
    end
end