---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 14.12.2021 18:24
---

function ChkCross (data, x1, y1, x2, y2, x3, y3, x4, y4)
    --local angle=AngleBetweenXY()
    local s1 = { x = x1, y = y1 }
    local e1 = { x = x2, y = y2 }
    local s2 = { x = x3, y = y3 }
    local e2 = { x = x4, y = y4 }
    local d = (s1.x - e1.x) * (s2.y - e2.y) - (s1.y - e1.y) * (s2.x - e2.x)
    local a = s1.x * e1.y - s1.y * e1.x
    local b = s2.x * e2.y - s2.y * e2.x
    local x = (a * (s2.x - e2.x) - (s1.x - e1.x) * b) / d
    local y = (a * (s2.y - e2.y) - (s1.y - e1.y) * b) / d
    local maxX = math.max(s1.x, s2.x, e1.x, e2.x)
    local minX = math.min(s1.x, s2.x, e1.x, e2.x)
    local maxY = math.max(s1.y, s2.y, e1.y, e2.y)
    local minY = math.min(s1.y, s2.y, e1.y, e2.y)
    if x > maxX or x < minX then
        return false
    end
    if y > maxY or y < minY then
        return false
    end
    local d1 = DistanceBetweenXY(x1, y1, x2, y2)
    local d2 = DistanceBetweenXY(x3, y3, x4, y4)
    local d1x = DistanceBetweenXY(x1, y1, x, y)
    local d2x = DistanceBetweenXY(x3, y3, x, y)
    if d1x > d1 then
        --print("далеко1")
        return false
    end
    if d2x > d2 then
        --print("далеко2")
        return false
    end
    --print(x, y)
    local v1 = GetVectorFromPoint2D(x1, y1, x2, y2)
    local v2 = GetVectorFromPoint2D(x3, y3, x4, y4)
    local angle = math.deg(v1:angleBetween(v2))
    --print(angle)
    if angle > 20 then
        CrossCast(data, x, y)
    else
        CrossCast(data, x, y)
        --print("парарллельные прямые")
    end

    --print(true)
    return true
end

function CrossCast(data, x, y)
    DestroyTimer(data.TimerLineDelay)
    DestroyEffect(AddSpecialEffect("Objects\\Spawnmodels\\Undead\\UndeadBlood\\UndeadBloodAbomination.mdl", x, y))
    local is, unit = UnitDamageArea(data.UnitHero, 500, x, y, 150)

    SetUnitExploded(unit, true)
    if not is then
        if IsUnitInRangeXY(data.UnitHero, x, y, 150) then
            --print("святой крест")
            HealUnit(data.UnitHero, 100, nil, "Abilities\\Spells\\Human\\HolyBolt\\HolyBoltSpecialArt")
            HolyCross(data)
            TriggerCastByName(data,"grandcross")
        end
    else
        TriggerCastByName(data,"deathcross")
    end
    TimerStart(CreateTimer(), TIMER_PERIOD64, false, function()
        data.line2 = nil
        data.line1 = nil
    end)
end

function HolyCross(data)
    if data.line2 then
       -- print("существует")
    else
        --print("уже очищено")
    end
    HolyLine(data,data.line2)
    HolyLine(data,data.line1)
end

function HolyLine(data,table)
    local x1, y1, x2, y2 = table[1], table[2], table[3], table[4]
    local angle = AngleBetweenXY(x1, y1, x2, y2) / bj_DEGTORAD
    local d = DistanceBetweenXY(x1, y1, x2, y2)
    local step = 80
    local current=0
    while true do
        current=current+step
        local x,y=MoveXY(x1,y1,current,angle)
        DestroyEffect(AddSpecialEffect("Abilities\\Spells\\Human\\HolyBolt\\HolyBoltSpecialArt", x, y))
        UnitDamageArea(data.UnitHero,100,x,y,80)
        if current >=d then
            break
        end
    end
end

