---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 14.12.2021 2:25
---
function CreateSquareCast(data, r, x, y, size)
    local z = GetTerrainZ(x, y) + 200
    local id = FourCC("DTfx")
    local big = false
    local blocks = {}
    local step = 64
    if size > 45 then
        big = true
        id = FourCC("DTrx")
    end
    local lift = CreateDestructableZ(id, x, y, z, 0, 1, 1) --DTrx большой
    x, y = GetDestructableX(lift), GetDestructableY(lift)

    if not big then
        -- print("Блокираторы")
        local k = 0
        local xs, ys = x - step * 2, y + step * 2
        for i = 1, 4 do
            k = k + 1
            blocks[k] = CreateDestructable(FourCC("YTlb "), xs + step * i, ys, 0, 1, 1)

        end
        blocks[9] = CreateDestructable(FourCC("YTlb "), xs + step, ys - step, 0, 1, 1)
        blocks[10] = CreateDestructable(FourCC("YTlb "), xs + step, ys - step * 2, 0, 1, 1)
        --Вторая линия
        xs, ys = x - step * 2, y - step * 1.5
        for i = 1, 4 do
            k = k + 1
            blocks[k] = CreateDestructable(FourCC("YTlb "), xs + step * i, ys, 0, 1, 1)

        end
        blocks[11] = CreateDestructable(FourCC("YTlb "), xs + step * 4, ys + step, 0, 1, 1)
        blocks[12] = CreateDestructable(FourCC("YTlb "), xs + step * 4, ys + step * 2, 0, 1, 1)

    else
        print("кастует крутую юльту")
    end

    TimerStart(CreateTimer(), 5, false, function()
        DestroySquare(lift, blocks)
    end)
    --Ytlb -- блокиратор
end

function DestroySquare(lift, blocks)
    --print(#blocks, " ась?")
    for i = 1, #blocks do
       -- print(i)
        RemoveDestructable(blocks[i])
    end
    RemoveDestructable(lift)
end