---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 13.12.2021 1:23
---
function FlameStrike(data, x, y, r)
    local damage = r / 2
    data.LastFlameStrikeR=r
    if damage<=250 then
        damage=200
    end
    if ChkStoneForGolem(data,x,y,r) then
        return
    end
    UnitDamageArea(data.UnitHero, damage, x, y, r)
    StunArea(data.UnitHero,x,y,r,1)
    local interval = 0.1
    local eff = AddSpecialEffect("Abilities\\Spells\\Human\\FlameStrike\\FlameStrike.mdl", x, y)
    local scale = r / 250

    if scale <= 0.7 then
        scale = 0.7
    end
    if scale >= 1.5 then
        scale = 1.5
    end
    BlzSetSpecialEffectMatrixScale(eff, scale, scale, scale)
    local sec = 3
    TimerStart(CreateTimer(), interval, true, function()
        sec = sec - interval
        UnitDamageArea(data.UnitHero, r / 40, x, y, r)
        if sec <= 0 then
            DestroyEffect(eff)
            DestroyTimer(GetExpiredTimer())
        end
    end)
end

function GetRadiusCircle(data, x, y)

    local r = 0
    for i = 1, #data.Points do
        r = r + DistanceBetweenXY(x, y, data.Points[i].x, data.Points[i].y)
    end
    r = r / #data.Points
    data.LastRadius=r
    return r
end

function ChkMediumRadius(Points, r, x, y)
    local delta = 50
    local isCircle = true
    for i = 1, #Points do
        local d = DistanceBetweenXY(x, y, Points[i].x, Points[i].y)
        if math.abs(d - r) > delta then
            --print("большой разброс, это не круг")
            isCircle = false
        else
            -- print("ok")
        end
    end
    return isCircle
end