---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 19.12.2021 17:22
---
function CreateIceLine(data)
    local effModel = "Abilities\\Spells\\Undead\\FreezingBreath\\FreezingBreathTargetArt"
    local eff = {}
    local points = data.Points
    --print(#data.Points)
    for i = 1, #points do
        eff[i]=AddSpecialEffect(effModel, points[i].x, points[i].y)
        --table.insert(eff, ))
    end
    local blast = "Abilities\\Spells\\Undead\\FrostNova\\FrostNovaTarget.mdl"
    local TimerImp = CreateTimer()
    local impact=true
    TimerStart(TimerImp, 0.3, true, function()
        for i = 1, #points do
            local x,y=points[i].x, points[i].y
            local is,enemy= UnitDamageArea(data.UnitHero,10,x,y,120)
            if enemy then
                if not IsUnitStunned(enemy) then
                    StunUnit(enemy,2,"frise")
                    DestroyEffect(AddSpecialEffect(blast,x,y))
                end
                --SetUnitMoveSpeed(enemy,50)
            end
        end
    end)

    TimerStart(CreateTimer(), 5, false, function()
        DestroyTimer(GetExpiredTimer())
        DestroyTimer(TimerImp)
        for i = 1, #eff do
            DestroyEffect(eff[i])
        end
    end)
end