---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 17.12.2021 20:58
---
function SandStorm(data, x, y)
    local eff = AddSpecialEffect("SandAura", x, y)
    local duration = 3
    TimerStart(CreateTimer(), TIMER_PERIOD64, true, function()
        local _, _, _, units = UnitDamageArea(data.UnitHero, 1, x, y, 250)
        for i = 1, #units do
            if not UnitAlive(units[i]) then
                local fh =GetFHByName(data,"Bag Card")
                if fh then
                    local ch=GetFrameCharges(fh)
                    for _=1,ch do
                        local new = CreateUnit(GetOwningPlayer(data.UnitHero), BugID[GetRandomInt(1,#BugID)], GetUnitX(units[i]), GetUnitY(units[i]), 0)
                        UnitApplyTimedLife(new, FourCC('BTLF'), 15)
                    end
                    --print("умер от SS создаём жуков",ch)
                end
            end
            local xu, yu = GetUnitXY(units[i])
            local z = 0
            local d = DistanceBetweenXY(x, y, xu, yu) - 2
            local angle = 3 + AngleBetweenXY(x, y, xu, yu) / bj_DEGTORAD
            local vector = Vector:new(x, y, z)
            local newVector = vector
            newVector = VectorSum(newVector, vector:yawPitchOffset(d, angle * (math.pi / 180), 0.0))
            SetUnitPositionSmooth(units[i], newVector.x, newVector.y)
        end
        duration = duration - TIMER_PERIOD64
        --print(duration)
        if duration <= 0 then
            DestroyTimer(GetExpiredTimer())
            DestroyEffect(eff)
            --print("end")
        end
    end)
end
