---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 14.12.2021 1:28
---
function CastLighting(data, max, radius, x, y)
    local hero = data.UnitHero
    local k = 0
    --local x,y=GetUnitXY(hero)
    local tableTriangle = {
        --data.AnglePoints[1].x,
        --data.AnglePoints[1].y,
        --data.AnglePoints[2].x,
        --data.AnglePoints[2].y,
        --data.Points[1].x,
        --data.Points[1].y
    }
    local enemy = FindNewEnemyForLight(nil, data, hero, radius, x, y)

    if enemy then
        TimerStart(CreateTimer(), 0.3, true, function()
            enemy = FindNewEnemyForLight(nil, data, hero, radius, x, y)
            if FindNewEnemyForLight(nil, data, hero, radius, x, y) then
                k = k + 1
            else
                DestroyTimer(GetExpiredTimer())
            end
            if k >= max then
                DestroyTimer(GetExpiredTimer())
            end
        end)
    end
end

function FindNewEnemyForLight(tableTriangle, data, hero, radius, xs, ys)
    local e = nil
    local k = 0
    local enemy = nil
    GroupEnumUnitsInRange(perebor, xs, ys, radius * 2, nil)
    while true do
        e = FirstOfGroup(perebor)
        if e == nil then
            break
        end
        if UnitAlive(e) and IsUnitEnemy(e, GetOwningPlayer(hero)) and not enemy then

            k = k + 1
            local x, y = GetUnitXY(e)
            if  true then --PointInTriangle(x, y, tableTriangle[1], tableTriangle[2], tableTriangle[3], tableTriangle[4], tableTriangle[5], tableTriangle[6])
                local eff = AddSpecialEffect("Doodads\\Cinematic\\Lightningbolt\\Lightningbolt", x, y)

                -- print("где эффект")
                TimerStart(CreateTimer(), 0.5, false, function()
                    DestroyEffect(eff)
                    PauseTimer(GetExpiredTimer())
                    DestroyTimer(GetExpiredTimer())
                end)

                UnitDamageTarget(hero, e, 50, true, false, ATTACK_TYPE_NORMAL, DAMAGE_TYPE_NORMAL, WEAPON_TYPE_WHOKNOWS)
                normal_sound("Abilities\\Spells\\Orc\\LightningBolt\\LightningBolt", x, y) -- не работает

            end
            --normal_sound("SystemGeneric\\ReceiveGold",x,y)
            enemy = e
        end
        GroupRemoveUnit(perebor, e)
    end
    return enemy
end