---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 07.01.2022 0:29
---
function InitMurlocAI()
    local _, _, t = FindUnitOfType(FourCC("n003"))
    for i = 1, #t do
        --print(GetUnitName(t[i]), i)
        StartMurlocAI(t[i])
    end
end

function StartMurlocAI(unit)
    TimerStart(CreateTimer(), GetRandomReal(3,5), true, function()
        if not UnitAlive(unit) then
            DestroyTimer(GetExpiredTimer())
        else
            local enemy = FindFirstEnemy(unit, 700)
            if enemy then
                -- print("цель найдена")
                IssueTargetOrder(unit, "attack",enemy)
                CastWaveWBar(unit, 3, enemy)
            else
                IssueImmediateOrder(unit,"stop")
            end
        end
    end)
end

function FindFirstEnemy(unit, range)
    local e = nil
    local result = false
    local xs, ys = GetUnitXY(unit)
    -- DestroyEffect(AddSpecialEffect("Abilities\\Spells\\NightElf\\Blink\\BlinkCaster.mdl", xs, ys))
    GroupEnumUnitsInRange(perebor, xs, ys, range, nil)
    while true do
        e = FirstOfGroup(perebor)
        if e == nil then
            break
        end

        if UnitAlive(e) and IsUnitEnemy(e, GetOwningPlayer(unit)) then
            --print("найден для сетки",GetUnitName(e))
            result = e
        end
        GroupRemoveUnit(perebor, e)
    end
    return result
end