---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 21.01.2022 15:08
---
---

function CreateTaskBoard()
    InitAllTask()
    local container = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), '', 0)
    BlzFrameSetParent(container, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetTexture(container, "Board\\Board", 0, true)
    local scale = 0.8
    local xs, ys = 0.8 * scale, 0.6 * scale
    BlzFrameSetSize(container, xs, ys)
    BlzFrameSetAbsPoint(container, FRAMEPOINT_CENTER, 0.4, 0.3)

    local text = BlzCreateFrameByType("TEXT", "ButtonChargesText", container, "", 0)
    local y = -0.065
    BlzFrameSetParent(text, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetText(text, "Доска объявлений")
    BlzFrameSetScale(text, 1.4)
    BlzFrameSetPoint(text, FRAMEPOINT_TOP, container, FRAMEPOINT_TOP, 0.00, y)
    BlzFrameSetTextColor(text, BlzConvertColor(255, 140, 240, 255))

    if true then
        local hero = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', container, '', 0)
        BlzFrameSetParent(hero, BlzGetFrameByName("ConsoleUIBackdrop", 0))
        BlzFrameSetTexture(hero, "Characters\\MagBack", 0, true)
        --scale = 0.8
        --xs, ys = 0.6 * scale, 0.4 * scale
        BlzFrameSetSize(hero, 0.2, 0.3)
        BlzFrameSetAbsPoint(hero, FRAMEPOINT_CENTER, 0.1, 0.1)
    end

    for i = 1, #BDTask do
        AddTask2Board(container, i)
    end

end

function AddTask2Board(container, number)

    local SelfFrame = BlzCreateFrameByType('GLUEBUTTON', 'FaceButton', container, 'ScoreScreenTabButtonTemplate', 0)
    local buttonIconFrame = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', SelfFrame, '', 0)
    BlzFrameSetParent(SelfFrame, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetParent(buttonIconFrame, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetAllPoints(buttonIconFrame, SelfFrame)
    BlzFrameSetTexture(buttonIconFrame, "Board\\TaskEmpty", 0, true)
    BlzFrameSetSize(SelfFrame, 0.4 / 5, 0.3 / 5)
    local x, y = GetRandomReal(-0.21, 0.21), GetRandomReal(-0.08, 0.08)
    BlzFrameSetPoint(SelfFrame, FRAMEPOINT_CENTER, container, FRAMEPOINT_CENTER, x, y)

    local text = BlzCreateFrameByType("TEXT", "ButtonChargesText", buttonIconFrame, "", 0)
    BlzFrameSetSize(text, 0.4 / 5 * 0.9, 0.3 / 5 * 0.95)
    BlzFrameSetText(text, "Нажмите на задание чтобы узнать подробности")
    BlzFrameSetPoint(text, FRAMEPOINT_CENTER, buttonIconFrame, FRAMEPOINT_CENTER, 0.00, -0.003)
    BlzFrameSetScale(text, 0.7)
    BlzFrameSetTextColor(text, BlzConvertColor(255, 0, 0, 0))
    BlzFrameSetEnable(text, false)
    TaskAddDifficult(buttonIconFrame, BDTask[number].difficulty,1)

    local ClickTrig = CreateTrigger()
    BlzTriggerRegisterFrameEvent(ClickTrig, SelfFrame, FRAMEEVENT_CONTROL_CLICK)
    TriggerAddAction(ClickTrig, function()
        BlzFrameSetEnable(BlzGetTriggerFrame(), false)
        BlzFrameSetEnable(BlzGetTriggerFrame(), true)
        --print(BDTask[number].name)
        CreateTaskDialogAndInfo(container, buttonIconFrame, number)
        --StopUnitMoving(data)
    end)


end

function TaskAddDifficult(parent, diff,scale)
    local step = 0.01*scale
    for i = 1, diff do
        --print(i)
        local df = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', parent, '', 0)
        --BlzFrameSetParent(df, BlzGetFrameByName("ConsoleUIBackdrop", 0))
        BlzFrameSetTexture(df, "Board\\Diff", 0, true)
        BlzFrameSetSize(df, step, step)
        BlzFrameSetPoint(df, FRAMEPOINT_BOTTOMRIGHT, parent, FRAMEPOINT_BOTTOMRIGHT, (-0.007*scale) - ((i - 1) * step), GetRandomReal(0.007, 0.01)*scale) --0-((i-0)-step)

    end
end

function CreateTaskDialogAndInfo(container, parent, number)

    local SelfFrame = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), '', 0)
    BlzFrameSetParent(SelfFrame, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetTexture(SelfFrame, "Board\\TaskEmpty", 0, true)
    BlzFrameSetSize(SelfFrame, 0.4 / 5, 0.3 / 5)
    BlzFrameSetPoint(SelfFrame, FRAMEPOINT_CENTER, parent, FRAMEPOINT_CENTER, 0, 0)

    local s = 5
    TimerStart(CreateTimer(), TIMER_PERIOD64, true, function()
        BlzFrameSetSize(SelfFrame, 0.4 / s, 0.3 / s)
        s = s - 0.5
        if s <= 0.5 then
            DestroyTimer(GetExpiredTimer())
            BlzFrameSetEnable(container, false)
            CreateCloseButton(SelfFrame)
            TaskAddDifficult(SelfFrame, BDTask[number].difficulty,5)
            CreateOKButton(SelfFrame, container, number)
            CreateIcoTask(SelfFrame, number)
            CreateDescriptionsTask(SelfFrame, s, number)

        end
    end)
end

function CreateCloseButton(parent)
    local SelfFrame = BlzCreateFrameByType('GLUEBUTTON', 'FaceButton', parent, 'ScoreScreenTabButtonTemplate', 0)
    local buttonIconFrame = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', SelfFrame, '', 0)
    --BlzFrameSetParent(SelfFrame, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    --BlzFrameSetParent(buttonIconFrame, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetAllPoints(buttonIconFrame, SelfFrame)
    BlzFrameSetTexture(buttonIconFrame, "Board\\Close", 0, true)
    BlzFrameSetSize(SelfFrame, GNext / 2, GNext / 2)
    BlzFrameSetPoint(SelfFrame, FRAMEPOINT_TOPRIGHT, parent, FRAMEPOINT_TOPRIGHT, -GNext / 4, -GNext / 2)

    local ClickTrig = CreateTrigger()
    BlzTriggerRegisterFrameEvent(ClickTrig, SelfFrame, FRAMEEVENT_CONTROL_CLICK)
    TriggerAddAction(ClickTrig, function()
        BlzFrameSetEnable(BlzGetTriggerFrame(), false)
        BlzFrameSetEnable(BlzGetTriggerFrame(), true)
        BlzDestroyFrame(SelfFrame)
        BlzDestroyFrame(parent)
    end)
end

function CreateOKButton(parent, container, number)
    local SelfFrame = BlzCreateFrameByType('GLUEBUTTON', 'FaceButton', parent, 'ScoreScreenTabButtonTemplate', 0)
    local buttonIconFrame = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', SelfFrame, '', 0)
    --BlzFrameSetParent(SelfFrame, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    --BlzFrameSetParent(buttonIconFrame, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetAllPoints(buttonIconFrame, SelfFrame)
    BlzFrameSetTexture(buttonIconFrame, "Board\\Ok", 0, true)
    BlzFrameSetSize(SelfFrame, GNext, GNext)
    BlzFrameSetPoint(SelfFrame, FRAMEPOINT_CENTER, parent, FRAMEPOINT_CENTER, 0, -GNext * 2.5)

    local ClickTrig = CreateTrigger()
    BlzTriggerRegisterFrameEvent(ClickTrig, SelfFrame, FRAMEEVENT_CONTROL_CLICK)
    TriggerAddAction(ClickTrig, function()
        BlzFrameSetEnable(BlzGetTriggerFrame(), false)
        BlzFrameSetEnable(BlzGetTriggerFrame(), true)
        BlzDestroyFrame(SelfFrame)
        BlzDestroyFrame(parent)
        BlzFrameSetVisible(container, false)
        print(BDTask[number].name, "выбрана как зона")
    end)
end

function CreateDescriptionsTask(parent, s, number)
    local text = BlzCreateFrameByType("TEXT", "ButtonChargesText", parent, "", 0)
    BlzFrameSetSize(text, 0.2 , 0.15 * 1)
    BlzFrameSetText(text, BDTask[number].descriptions .. "\nНаграда: " .. BDTask[number].reward.." эйрис")
    BlzFrameSetScale(text, 1.2)
    BlzFrameSetPoint(text, FRAMEPOINT_CENTER, parent, FRAMEPOINT_CENTER, 0.02, 0)
    BlzFrameSetTextColor(text, BlzConvertColor(255, 0, 0, 0))
    BlzFrameSetEnable(text, false)
end

function CreateIcoTask(SelfFrame, number)
    local texture=BDTask[number].ico
    local ico = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', SelfFrame, '', 0)
    if not texture then
        texture="ReplaceableTextures\\CommandButtons\\BTNSelectHeroOn"
    end
    BlzFrameSetTexture(ico, texture, 0, true)
    BlzFrameSetSize(ico, GNext*2, GNext*2)
    BlzFrameSetPoint(ico, FRAMEPOINT_TOPLEFT, SelfFrame, FRAMEPOINT_TOPLEFT, GNext/2, -GNext)
end
