---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 21.01.2022 17:55
---
function InitAllTask()
    BDTask = {
        [1] = {
            name         = "Bear-OnePunchMan",
            descriptions = "Победите медведя ванпанчмена",
            difficulty   = 5,
            reward       = 300000
        },
        [2] = {
            name         = "Wood from lumber",
            descriptions = "Принесите 100 древесины",
            difficulty   = 1,
            reward       = 10000
        },
        [3] = {
            name         = "Death Knight",
            descriptions = "Убить рыцаря смерти",
            difficulty   = 6,
            reward       = 1000000
        },
        [4] = {
            name         = "Purge",
            descriptions = "Очистите пруд от загрязнения",
            difficulty   = 3,
            reward       = 10000
        },
        [5] = {
            name         = "Where wolf",
            descriptions = "Отыщите потерявшегося щенка и приведите его домой",
            difficulty   = 1,
            reward       = 10000
        },
        [6] = {
            name         = "Giant frog",
            descriptions = "Убить 5 гигантских жаб",
            difficulty   = 3,
            reward       = 110000
        },
        [7] = {
            name         = "Rogue",
            descriptions = "Разобраться с шайкой разбойников",
            difficulty   = 2,
            reward       = 60000
        },
        [8] = {
            name         = "Turtle Egg",
            descriptions = "Найти 8 гигантских черепаших яиц",
            difficulty   = 1,
            reward       = 80000
        },
        [9] = {
            name         = "Griffon",
            descriptions = "Прогнать грифона с рынка",
            difficulty   = 1,
            reward       = 80000
        },
        [10] = {
            name         = "Vegan",
            descriptions = "На ворота города Аксис напала капуста, не дайте капусте проникнуть во внутрь",
            difficulty   = 2,
            reward       = 200000
        }


    }
end