---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 24.12.2021 22:58
---
function CreateFlyFrame(data, parent, textTip)
    --print("где подсказка?")
    local text = BlzCreateFrameByType("TEXT", "ButtonChargesText", parent, "", 0)
    local y=0.005
    BlzFrameSetParent(text, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetText(text, textTip)
    BlzFrameSetScale(text, 1.4)
    BlzFrameSetPoint(text, FRAMEPOINT_TOP, parent, FRAMEPOINT_TOP, 0.00, y)
    BlzFrameSetTextColor(text, BlzConvertColor(255, 140, 140, 255))
    if data.ShowDownPanel then
        BlzFrameSetVisible(text,GetLocalPlayer() == Player(data.pid))
    else
         BlzFrameSetVisible(text,false)
    end
    local a=0
    TimerStart(CreateTimer(), TIMER_PERIOD64, true, function()
        a=a+10
        --print(a)
        BlzFrameSetAlpha(text,a)
        if a>=250 then
           -- print("revers")
            --BlzDestroyFrame(text)
            TimerStart(CreateTimer(), TIMER_PERIOD64, true, function()
                a=a-5
                BlzFrameSetAlpha(text,a)
               -- print(a)
                if a<=0 then
                    --print("destroy",y)
                    DestroyTimer(GetExpiredTimer())
                    BlzDestroyFrame(text)
                end
            end)
            DestroyTimer(GetExpiredTimer())
        end
    end)

    TimerStart(CreateTimer(), TIMER_PERIOD64, true, function()
        y=y+0.0005
        BlzFrameSetPoint(text, FRAMEPOINT_TOP, parent, FRAMEPOINT_TOP, 0.00, y)
        if y>0.2 then
            DestroyTimer(GetExpiredTimer())
        end
        --print(y)
    end)
end