---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 16.12.2021 21:48
---
function CreateDownInterface(data)
    local container = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), '', 0)
    AddDownInterfaceElement(data, container, "line", 50)
    AddDownInterfaceElement(data, container, "circle", 100)
    AddDownInterfaceElement(data, container, "curve", 150)
    AddDownInterfaceElement(data, container, "triangle", 150)
    AddDownInterfaceElement(data, container, "wave", 100)
    AddDownInterfaceElement(data, container, "squae", 200)
    AddDownInterfaceElement(data, container, "smallrocks", 20)
    AddDownInterfaceElement(data, container, "CircleHeal", 150)
    AddDownInterfaceElement(data, container, "clock", 200)
    AddDownInterfaceElement(data, container, "icewall", 500)
    AddDownInterfaceElement(data, container, "deathcross", 300)
    AddDownInterfaceElement(data, container, "grandcross", 300)
    AddDownInterfaceElement(data, container, "z", 200)
    AddDownInterfaceElement(data, container, "m", 500)
    AddDownInterfaceElement(data, container, "curvecircle", 300)
    AddDownInterfaceElement(data, container, "golem", 500)
    BlzFrameSetVisible(container, GetLocalPlayer() == Player(data.pid))
    CreateHideButton(data, container)
end

function AddDownInterfaceElement(data, parent, name, weight)
    local step = 0.039
    if not data.nextElement then
        data.nextElement = 0
        data.SpellsName = {}-- таблица содержит фреймы
        data.SpellsFH = {}
        data.WeightSpellTable = {} --таблица весов
        data.PreviousCast = ""
    end
    table.insert(data.WeightSpellTable, weight)
    data.nextElement = data.nextElement + 1
    data.SpellsName[data.nextElement] = name
    data.SpellsFH[data.nextElement] = CreateSimpleFrameGlue(data.nextElement * step, 0.02, name, parent)
end

function CreateHideButton(data, container)
    local texture2 = "dds\\toleft"--"ReplaceableTextures\\CommandButtons\\BTNCryptFiendBurrow.blp"
    local texture = "dds\\toright"--"ReplaceableTextures\\CommandButtons\\BTNCryptFiendUnBurrow.blp"
    local SelfFrame = BlzCreateFrameByType('GLUEBUTTON', 'FaceButton', BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), 'ScoreScreenTabButtonTemplate', 0)
    local buttonIconFrame = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', SelfFrame, '', 0)
    data.ShowDownPanel = true
    BlzFrameSetParent(SelfFrame, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetParent(buttonIconFrame, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetAllPoints(buttonIconFrame, SelfFrame)
    BlzFrameSetTexture(buttonIconFrame, texture, 0, true)
    BlzFrameSetSize(SelfFrame, GNext, GNext)
    BlzFrameSetVisible(SelfFrame, GetLocalPlayer() == Player(data.pid))
    --BlzFrameSetPoint(SelfFrame, FRAMEPOINT_RIGHT, parent, FRAMEPOINT_RIGHT, GNext, 0.00)
    BlzFrameSetAbsPoint(SelfFrame, FRAMEPOINT_CENTER, -0.11, GNext / 2)

    ---Подсказка
    local text = BlzCreateFrameByType("TEXT", "ButtonChargesText", SelfFrame, "", 0)
    BlzFrameSetParent(text, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetText(text, "Скрыть")
    BlzFrameSetScale(text, 1)
    BlzFrameSetPoint(text, FRAMEPOINT_TOP, SelfFrame, FRAMEPOINT_TOP, 0.00, 0.01)

    local ClickTrig = CreateTrigger()
    BlzTriggerRegisterFrameEvent(ClickTrig, SelfFrame, FRAMEEVENT_CONTROL_CLICK)
    TriggerAddAction(ClickTrig, function()
        BlzFrameSetEnable(BlzGetTriggerFrame(), false)
        BlzFrameSetEnable(BlzGetTriggerFrame(), true)
        if data.ShowDownPanel then
            data.ShowDownPanel = false
            BlzFrameSetVisible(container, false)
            BlzFrameSetTexture(buttonIconFrame, texture2, 0, true)
            BlzFrameSetText(text, "Показать")
        else
            data.ShowDownPanel = true
            BlzFrameSetVisible(container, GetLocalPlayer() == GetTriggerPlayer())
            BlzFrameSetTexture(buttonIconFrame, texture, 0, true)
            BlzFrameSetText(text, "Скрыть")
        end
        StopUnitMoving(data)
    end)

    local TrigMOUSE_ENTER = CreateTrigger()
    BlzTriggerRegisterFrameEvent(TrigMOUSE_ENTER, SelfFrame, FRAMEEVENT_MOUSE_ENTER)
    TriggerAddAction(TrigMOUSE_ENTER, function()
        --print("показать подсказку ",flag)
    end)
    local TrigMOUSE_LEAVE = CreateTrigger()
    BlzTriggerRegisterFrameEvent(TrigMOUSE_LEAVE, SelfFrame, FRAMEEVENT_MOUSE_LEAVE)
    TriggerAddAction(TrigMOUSE_LEAVE, function()
        --print("убрать подсказку")
    end)

    return SelfFrame, buttonIconFrame
end