---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 30.12.2021 22:38
---
function CreateWarningMessage(data, message)
    local x, y = 0.4, 0.2
    local ico = "dds\\Warning"
    local frame = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), '', 0)

    BlzFrameSetTexture(frame, ico, 0, true)
    BlzFrameSetSize(frame, 0.2, 0.1)
    BlzFrameSetAbsPoint(frame, FRAMEPOINT_CENTER, x, y)

    local text = BlzCreateFrameByType("TEXT", "ButtonChargesText", frame, "", 0)
    BlzFrameSetPoint(text, FRAMEPOINT_CENTER, frame, FRAMEPOINT_CENTER, 0.0, 0.0)
    BlzFrameSetText(text, "Warning: Don't spam")
    data.LastCastName=""
    BlzFrameSetVisible(frame, GetLocalPlayer() == Player(data.pid))

    --звук разряженной батарейки
    local s = "warning"
    if not GetLocalPlayer() == Player(data.pid) then
        s = ""
    end

    normal_sound(s, GetUnitXY(data.UnitHero))
    local sec = 2
    local scale = 1
    local sin=0
    TimerStart(CreateTimer(), TIMER_PERIOD64, true, function()
        sec = sec - TIMER_PERIOD64
        sin=sin+0.1
        scale = 1 + math.abs(math.sin(sin))/2
        BlzFrameSetScale(frame, scale)

        if sec <= 0 then
            BlzDestroyFrame(text)
            BlzDestroyFrame(frame)
            DestroyTimer(GetExpiredTimer())
        end
    end)
end