---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 22.01.2022 19:49
---
function InitActiveSpellPanel(data)
    CreateKazumaSpellPanel(data)
    CreateAquaSpellPanel(data)
    CreateAquaSpellDarkness(data)
end

function CreateAquaSpellDarkness(data)
    data.ContainerSpellDarkness = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), '', 0)
    local x,y=0.78,0.06
    local name="Darkness"
    CreateAbilityButton(data, data.ContainerSpellDarkness, x, y,name,"Space")
    CreateAbilityButton(data, data.ContainerSpellDarkness, x+GNext, y+GNext/3,name,"Rmb")
    CreateAbilityButton(data, data.ContainerSpellDarkness, x+GNext*2, y+(GNext/3)*2,name,"Lmb")
    CreateAbilityButton(data, data.ContainerSpellDarkness, x+GNext*3, y+(GNext/3)*3,name,"Q")
    y=0.012
    CreateAbilityButton(data, data.ContainerSpellDarkness, x+GNext*1, y+(GNext/3)*1,name,"R")
    CreateAbilityButton(data, data.ContainerSpellDarkness, x+GNext*2, y+(GNext/3)*2,name,"E")
    --CreateAbilityButton(data, data.ContainerSpellDarkness, x+GNext*3, y+(GNext/3)*3,name,"F")
    BlzFrameSetVisible(data.ContainerSpellDarkness,false)
end

function CreateAquaSpellPanel(data)
    data.ContainerSpellAqua = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), '', 0)
    local x,y=0.78,0.06
    local name="Aqua"
    CreateAbilityButton(data, data.ContainerSpellAqua, x, y,name,"Space")
    CreateAbilityButton(data, data.ContainerSpellAqua, x+GNext, y+GNext/3,name,"Rmb")
    CreateAbilityButton(data, data.ContainerSpellAqua, x+GNext*2, y+(GNext/3)*2,name,"Lmb")
    CreateAbilityButton(data, data.ContainerSpellAqua, x+GNext*3, y+(GNext/3)*3,name,"Q")
    y=0.012
    CreateAbilityButton(data, data.ContainerSpellAqua, x+GNext*1, y+(GNext/3)*1,name,"R")
    --CreateAbilityButton(data, data.ContainerSpellAqua, x+GNext*2, y+(GNext/3)*2,name,"E")
    BlzFrameSetVisible(data.ContainerSpellAqua,false)
end

function CreateKazumaSpellPanel(data)
    data.ContainerSpellKazuma = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), '', 0)
    local x,y=0.78,0.06
    local name="Kazuma"
    CreateAbilityButton(data, data.ContainerSpellKazuma, x, y,name,"Space")
    CreateAbilityButton(data, data.ContainerSpellKazuma, x+GNext, y+GNext/3,name,"Rmb")
    CreateAbilityButton(data, data.ContainerSpellKazuma, x+GNext*2, y+(GNext/3)*2,name,"Lmb")
    CreateAbilityButton(data, data.ContainerSpellKazuma, x+GNext*3, y+(GNext/3)*3,name,"Q")
    y=0.012
    CreateAbilityButton(data, data.ContainerSpellKazuma, x+GNext*1, y+(GNext/3)*1,name,"E")
    CreateAbilityButton(data, data.ContainerSpellKazuma, x+GNext*2, y+(GNext/3)*2,name,"R")
    CreateAbilityButton(data, data.ContainerSpellKazuma, x+GNext*3, y+(GNext/3)*3,name,"F")
    --BlzFrameSetVisible(data.ContainerSpellKazuma,false)
end

function CreateAbilityButton(data, container, x, y,name,key)
    --print("where")
    local SelfFrame = BlzCreateFrameByType('GLUEBUTTON', 'FaceButton', container, 'ScoreScreenTabButtonTemplate', 0)
    local buttonIconFrame = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', SelfFrame, '', 0)
    BlzFrameSetParent(SelfFrame, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetParent(buttonIconFrame, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetParent(container, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetAllPoints(buttonIconFrame, SelfFrame)
    BlzFrameSetTexture(buttonIconFrame, "Textures\\"..name.."\\"..key, 0, true)
    BlzFrameSetSize(SelfFrame, GNext, GNext)

    --BlzFrameSetPoint(SelfFrame, FRAMEPOINT_CENTER, container, FRAMEPOINT_CENTER, x, y)
    BlzFrameSetAbsPoint(SelfFrame, FRAMEPOINT_CENTER, x, y)

    local ClickTrig = CreateTrigger()
    BlzTriggerRegisterFrameEvent(ClickTrig, SelfFrame, FRAMEEVENT_CONTROL_CLICK)
    TriggerAddAction(ClickTrig, function()
        BlzFrameSetEnable(BlzGetTriggerFrame(), false)
        BlzFrameSetEnable(BlzGetTriggerFrame(), true)
        StopUnitMoving(data)
    end)

    local TrigMOUSE_ENTER = CreateTrigger()
    BlzTriggerRegisterFrameEvent(TrigMOUSE_ENTER, SelfFrame, FRAMEEVENT_MOUSE_ENTER)
    TriggerAddAction(TrigMOUSE_ENTER, function()
        --print("показать подсказку ",flag)
    end)
    local TrigMOUSE_LEAVE = CreateTrigger()
    BlzTriggerRegisterFrameEvent(TrigMOUSE_LEAVE, SelfFrame, FRAMEEVENT_MOUSE_LEAVE)
    TriggerAddAction(TrigMOUSE_LEAVE, function()
        --print("убрать подсказку")
    end)

    ---Подсказка
    local text = BlzCreateFrameByType("TEXT", "ButtonChargesText", SelfFrame, "", 0)
    BlzFrameSetParent(text, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetText(text, key)
    BlzFrameSetScale(text, 1)
    BlzFrameSetPoint(text, FRAMEPOINT_TOP, SelfFrame, FRAMEPOINT_TOP, 0.00, 0.01)

end